### ISSUE TITLE
Lines duplicates when you switch another app and come back

### ISSUE THREAD

**Issue by brburak** [massivemadness/Squircle-CE#163] opened 2023-02-10 23:00 UTC
**App Version:**
2022.2.1

**Affected Device(s):**
Oneplus 8 android 13

**Describe the bug**
Lines duplicates when you switch another app and come back

**To Reproduce**
1. Open an Python file
2. Switch to another app 
3. Come back

**Expected behavior**
![Screenshot_2023-02-11-01-59-06-12_c21c09edd991f56f77ab49539e5515b2](https://user-images.githubusercontent.com/39774066/218218380-4c4a1ff3-f0a6-45d9-b3ae-836becc99fcc.jpg)
![Screenshot_2023-02-11-01-59-35-56_c21c09edd991f56f77ab49539e5515b2](https://user-images.githubusercontent.com/39774066/218218400-285b3398-4a07-48b7-a5d8-67673413d2fc.jpg)

First picture is orijinal file.
Second is when switch to another application.

**Comment by massivemadness** [comment] 2023-02-11 08:22
Looks like a line break issue. Which line break are you using?

**Comment by brburak** [comment] 2023-02-11 08:36
> Looks like a line break issue. Which line break was used in original file?

Orijinal file was written from Windows. I also tried other linebreak settings but same issue continues.

Also thank you for the great app ❤️

**Comment by massivemadness** [comment] 2023-02-11 16:52
@brburak Can you send me this file (or any other) so I could test it on my device?

**Comment by brburak** [comment] 2023-02-11 17:33
11 Şub 2023 Cmt 19:52 tarihinde Dmitrii Rubtsov ***@***.***>
şunu yazdı:

**Comment by brburak** [comment] 2023-02-11 17:39
On the first picture look at the lines 16-17, 26-27, 31-33 etc. May be something is wrong about there.

**Comment by massivemadness** [comment] 2023-02-11 18:12
@brburak I understand, but I can't reproduce it. If you send me this python script I can try on my device

**Comment by brburak** [comment] 2023-02-11 18:17
https://drive.google.com/file/d/1ktUzdTWw9KjdWr7CR4uqUtRolAUdO3j6/view?usp=drivesdk

**Comment by massivemadness** [comment] 2023-02-12 10:45
Fixed in [v2023.1.0](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.0)

**Closed by massivemadness** 2023-02-12 10:45 UTC
Labels: bug

**Comment by brburak** [comment] 2023-02-12 12:52
You are a King bro 🙏
